import { createContext, useContext, useState, useEffect } from 'react';
import type { ReactNode } from 'react';

export type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations = {
  en: {
    // Header
    'header.home': 'Ticket Ballot',
    'header.register': 'Register/Login',
    'header.adminLogin': 'Admin Login',
    'header.createGroup': 'Create Group',
    'header.myStatus': 'My Status',
    'header.results': 'Results',
    'header.join': '🔐 Join',
    'header.dashboard': '⚙️ Dashboard',
    'header.logout': '🚪 Logout',
    'header.adminName': 'Admin: {name}',
    'header.userLogout': 'logout',
    'header.openMainMenu': 'Open main menu',
    
    // Landing Page
    'landing.title': 'Fair & Transparent',
    'landing.subtitle': 'Ticket Ballot',
    'landing.description': 'Get your chance at tickets through our randomized ballot system. Form groups, submit entries, and let fairness decide.',
    'landing.participants': 'Participants',
    'landing.groups': 'Groups Formed',
    'landing.ballotComplete': 'Ballot Complete',
    'landing.howItWorks': 'How it works:',
    'landing.step1': 'Register your interest',
    'landing.step2': 'Form groups (1-3 people)',
    'landing.step3': 'Random ballot determines order',
    'landing.joinBallot': 'Join the Ballot',
    'landing.joinDescription': 'Register now to participate in the fair ticket ballot system.',
    'landing.registerLogin': 'Register / Login',
    'landing.checkStatus': 'Check Status',
    'landing.administrator': 'Administrator?',
    'landing.adminLogin': '🔐 Admin Login',
    'landing.youreRegistered': "You're Registered!",
    'landing.readyToForm': 'Ready to form a group or check your status.',
    'landing.createJoinGroup': 'Create/Join Group',
    'landing.checkMyStatus': 'Check My Status',
    'landing.adminMode': 'Admin Mode',
    'landing.adminDescription': 'Manage participants, groups, and run the ballot.',
    'landing.goToDashboard': 'Go to Dashboard',
    'landing.viewResults': 'View Ballot Results',
    
    // Status Page
    'status.youreRegistered': "You're Registered!",
    'status.noGroupYet': 'No Group Yet',
    'status.noGroupDescription': "You haven't created or joined a group yet. You need to be part of a group to participate in the ballot.",
    'status.whatsNext': "What's next?",
    'status.createGroupStep': 'Create a group',
    'status.becomeRepresentative': 'Become a representative and submit a ballot entry',
    'status.waitForApproval': 'Wait for approval',
    'status.adminValidation': 'Admin will validate your group members',
    'status.ballotDraw': 'Ballot draw',
    'status.randomSelection': 'Random selection determines allocation order',
    'status.createGroupButton': 'Create Group',
    'status.backToHome': 'Back to Home',
    'status.checkStatus': 'Check Your Status',
    'status.enterEmail': 'Enter your email to see your participation status',
    'status.emailAddress': 'Email Address',
    'status.checkStatusButton': 'Check Status',
    'status.notRegisteredYet': 'Not registered yet?',
    'status.registerNow': 'Register now →',
    'status.notRegistered': 'Not Registered',
    'status.emailNotRegistered': 'The email {email} is not registered for this ballot.',
    'status.registerNowButton': 'Register Now',
    'status.viewResults': 'View Results',
    'status.yourStatus': 'Your Status',
    'status.registered': 'Registered',
    'status.readyToParticipate': 'Ready to participate',
    'status.groupApproved': 'Group Approved',
    'status.ballotComplete': 'Ballot Complete',
    'status.pendingApproval': 'Pending Approval',
    'status.readyToDraw': 'Ready to Draw',
    'status.drawComplete': 'Draw Complete',
    'status.readyForBallotDraw': 'Ready for ballot draw',
    'status.resultsAvailable': 'Results available',
    'status.waitingForAdminValidation': 'Waiting for admin validation',
    'status.clickToDrawPosition': 'Click to draw your position!',
    'status.waitingForRepresentative': 'Waiting for representative to draw',
    'status.positionDrawn': 'Position {position} drawn',
    'status.groupDetails': 'Group Details',
    'status.representative': 'Representative',
    'status.groupSize': 'Group Size',
    'status.members': 'Members',
    'status.you': 'You',
    'status.rep': 'Rep',
    'status.timeToDraw': 'Time to Draw!',
    'status.groupReadyForBallot': 'Your Group is Ready for Ballot Draw',
    'status.asRepresentative': 'As the representative of {groupName}, you can now draw your position in the ballot.',
    'status.clickToDraw': 'Click the button below to randomly draw your group\'s position.',
    'status.drawing': 'Drawing...',
    'status.drawPosition': 'Draw Position',
    'status.ballotStatus': 'Ballot Status',
    'status.ballotInProgress': 'Ballot in Progress',
    'status.groupCompletedDraw': 'Your group has completed the draw. Waiting for other groups to finish.',
    'status.canDrawNow': 'You can now draw your position above.',
    'status.ballotResults': 'Ballot Results',
    'status.positionInQueue': 'Your group is #{position} in the allocation queue',
    'status.drawnOn': 'Drawn on',
    'status.totalGroups': 'Total Groups',
    'status.totalParticipants': 'Total Participants',
    'status.viewFullResults': 'View Full Results',
    'status.refreshStatus': 'Refresh Status',
    
    // Group Formation Page
    'group.create.title': 'Create Group',
    'group.create.description': 'Form a group of up to 3 people to participate in the ballot',
    'group.create.tab': 'Create Group',
    'group.join.title': 'Join Group',
    'group.join.description': 'Join an existing group that needs more members',
    'group.join.tab': 'Join Group',
    'group.create.membersTitle': 'Group Members',
    'group.create.youRepresentative': 'You (Representative)',
    'group.create.rep': 'Rep',
    'group.create.remove': 'Remove',
    'group.create.addParticipants': 'Add Registered Participants:',
    'group.create.selectParticipant': 'Select a participant...',
    'group.create.addByEmail': 'Or add by email:',
    'group.create.memberPlaceholder': 'Enter email address',
    'group.create.add': 'Add',
    'group.create.groupSize': 'Group Size',
    'group.create.membersLower': 'members',
    'group.create.registeredRequired': 'All members must be registered participants',
    'group.create.submit': 'Create Group',
    'group.create.submitting': 'Creating...',
    'group.create.cancel': 'Cancel',
    'group.create.invalidEmail': 'Please enter a valid email address',
    'group.create.duplicateEmail': 'This email is already in the group',
    'group.create.maxMembers': 'Group can have maximum 3 members',
    'group.create.memberCount': 'Groups must have at least 1 member (yourself)',
    'group.join.availableGroups': 'Available Groups',
    'group.join.noGroups': 'No groups available to join',
    'group.join.createInstead': 'Try creating your own group instead',
    'group.join.tip': 'Tip',
    'group.join.submit': 'Join Group',
    'group.join.submitting': 'Joining...',
    'group.accessRequired': 'Registration Required',
    'group.registerFirst': 'You need to register first before creating or joining a group.',
    'group.registerNow': 'Register Now',
    'group.ballotComplete': 'Ballot Complete',
    'group.formationClosed': 'Group formation is closed. The ballot has been completed.',
    'group.viewResults': 'View Results',
    'group.existing.title': 'Your Group',
    'group.existing.description': 'You are already part of a group',
    'group.existing.details': 'Group Details',
    'group.existing.representative': 'Representative',
    'group.existing.you': 'You',
    'group.existing.groupSize': 'Group Size',
    'group.existing.members': 'members',
    'group.existing.status': 'Status',
    'group.existing.statusPending': 'Pending Approval',
    'group.existing.statusApproved': 'Approved',
    'group.existing.statusLocked': 'Ballot Complete',
    'group.existing.membersTitle': 'Members',
    'group.existing.rep': 'Rep',
    'group.existing.viewFullStatus': 'View Full Status',
    'group.existing.backToHome': 'Back to Home',
    'group.error': 'Error',
    'group.groupRepresentative': 'Representative: {name}',
    'group.groupCreated': 'Created: {date}',
    'group.groupMembers': 'Members: {members}',
    'group.spacesAvailable': '{count} space{plural} available',
    'group.selectGroupTip': 'Select a group to join and click Join Group',
    
    // Demo Data
    'demo.loadDemoData': '🧪 Load Demo Data',
    'demo.loadSampleData': 'Load sample data for testing',
    'demo.dataLoaded': 'Demo data loaded! You can now test the application.',
    'demo.failedToLoad': 'Failed to load demo data: {error}',
    
    // User Auth Page
    'userAuth.joinBallot': 'Join the Ballot',
    'userAuth.welcomeBack': 'Welcome Back',
    'userAuth.registerDescription': 'Register to participate in the ticket ballot',
    'userAuth.loginDescription': 'Login with your registered email',
    'userAuth.register': 'Register',
    'userAuth.login': 'Login',
    'userAuth.createAccount': 'Create Your Account',
    'userAuth.loginToAccount': 'Login to Your Account',
    'userAuth.emailAddress': 'Email Address',
    'userAuth.emailPlaceholder': 'your@email.com',
    'userAuth.wechatId': 'WeChat ID',
    'userAuth.wechatPlaceholder': 'Enter your WeChat ID',
    'userAuth.createAccountBtn': 'Create Account',
    'userAuth.loginBtn': 'Login',
    'userAuth.creatingAccount': 'Creating Account...',
    'userAuth.loggingIn': 'Logging in...',
    'userAuth.noPasswordRequired': '📧 No password required - just use your email to login later',
    'userAuth.passwordFreeLogin': '🔒 Password-free login - we\'ll recognize your email',
    'userAuth.emailForLogin': 'Enter the email you used to register',
    'userAuth.backToHome': '← Back to Home',
    'userAuth.needAdminAccess': 'Need admin access?',
    'userAuth.adminLogin': 'Admin Login',
    
    // Admin Login Page
    'adminLogin.title': 'Administrator Login',
    'adminLogin.description': 'Secure access to ballot administration panel',
    'adminLogin.adminAccessOnly': '🔒 Admin Access Only',
    'adminLogin.username': 'Username',
    'adminLogin.usernamePlaceholder': 'Enter admin username',
    'adminLogin.password': 'Password',
    'adminLogin.passwordPlaceholder': 'Enter password',
    'adminLogin.signIn': 'Sign In',
    'adminLogin.signingIn': 'Signing In...',
    'adminLogin.backToSite': '← Back to Public Site',
    'adminLogin.regularUser': 'Regular user?',
    'adminLogin.userRegistration': 'User Registration/Login',
    'adminLogin.accessOnly': 'Admin Access Only',
    'adminLogin.adminAccessDescription': 'This is a secure admin area. Only authorized administrators can access the system management features.',
    'adminLogin.error': 'Error',
    'adminLogin.defaultAccounts': '🚀 Default Login Accounts',
    'adminLogin.standardAdmin': 'Standard Admin:',
    'adminLogin.superAdmin': 'Super Admin:',
    'adminLogin.changePassword': '⚠️ Please change default passwords after first login',
    'adminLogin.firstTimeSetup': '🚀 First Time Setup',
    'adminLogin.manageParticipants': 'Manage Participants',
    'adminLogin.manageDescription': 'Add, remove, and view all participants',
    'adminLogin.runBallot': 'Run Ballot',
    'adminLogin.runDescription': 'Execute fair randomized ballot draws',
    'adminLogin.viewResultsFeature': 'View Results',
    'adminLogin.viewDescription': 'Export and analyze ballot results',
    
    // Admin Navigation
    'admin.dashboard': 'Dashboard',
    'admin.settings': 'Admin Settings',
    
    // Admin Dashboard
    'adminDashboard.title': 'Administration Dashboard',
    'adminDashboard.welcome': 'Welcome to the Ballot Administration Panel',
    'adminDashboard.totalParticipants': 'Total Participants',
    'adminDashboard.pendingGroups': 'Pending Groups',
    'adminDashboard.approvedGroups': 'Approved Groups',
    'adminDashboard.lockedGroups': 'Locked Groups',
    'adminDashboard.overview': 'Overview',
    'adminDashboard.participants': 'Participants',
    'adminDashboard.groups': 'Groups',
    'adminDashboard.ballot': 'Ballot',
    'adminDashboard.startBallot': 'Start Ballot Session',
    'adminDashboard.viewResults': 'View Results',
    'adminDashboard.recentActivity': 'Recent Activity',
    'adminDashboard.addParticipant': 'Add Participant',
    'adminDashboard.email': 'Email',
    'adminDashboard.wechatId': 'WeChat ID',
    'adminDashboard.addUser': 'Add User',
    'adminDashboard.adding': 'Adding...',
    'adminDashboard.participantsList': 'Participants List',
    'adminDashboard.groupsList': 'Groups List',
    'adminDashboard.ballotStatus': 'Ballot Status',
    'adminDashboard.groupCreated': 'Group created ({count} members)',
    'adminDashboard.locked': 'locked',
    'adminDashboard.ballotCompleted': '✅ Ballot completed with {count} groups',
    'adminDashboard.add': 'Add',
    'adminDashboard.addButton': 'Add',
    'adminDashboard.remove': 'Remove',
    'adminDashboard.edit': 'Edit',
    'adminDashboard.approve': 'Approve',
    'adminDashboard.reject': 'Reject',
    'adminDashboard.representative': 'Representative',
    'adminDashboard.members': 'members',
    'adminDashboard.member': 'member',
    'adminDashboard.status': 'Status',
    'adminDashboard.actions': 'Actions',
    'adminDashboard.role': 'Role',
    'adminDashboard.user': 'User',
    'adminDashboard.noActivity': 'No recent activity',
    'adminDashboard.createdAt': 'Created',
    'adminDashboard.statusInGroup': 'In Group',
    'adminDashboard.statusNoGroup': 'No Group',
    'adminDashboard.noActivityYet': 'No activity yet',
    'adminDashboard.quickActions': 'Quick Actions',
    'adminDashboard.makeRepresentative': 'Make Representative',
    'adminDashboard.removeRepresentativeRole': 'Remove Representative Role',
    'adminDashboard.userRole': 'User',
    'adminDashboard.repRole': 'Rep',
    'adminDashboard.emailAddress': 'Email Address',
    'adminDashboard.wechatIdLabel': 'WeChat ID',
    'adminDashboard.wechatIdPlaceholder': 'Enter WeChat ID for identification',
    'adminDashboard.addedBy': 'Added By',
    'adminDashboard.date': 'Date',
    'adminDashboard.groupStatus': 'Group Status',
    'adminDashboard.groupMembers': 'Group ({count} members)',
    'adminDashboard.readyForBallot': 'Ready for ballot',
    'adminDashboard.waitingForDraw': 'Waiting for rep to draw',
    'adminDashboard.positionDrawn': 'Position #{position} drawn',
    'adminDashboard.ballotCompletedStatus': 'Ballot completed',
    'adminDashboard.noGroupsYet': 'No groups created yet',
    'adminDashboard.noParticipantsYet': 'No participants yet',
    'adminDashboard.participantsHeader': 'Participants ({count})',
    'adminDashboard.roleRepresentative': 'Representative',
    'adminDashboard.roleUser': 'User',
    'adminDashboard.addedByAdmin': 'Admin',
    'adminDashboard.addedBySelf': 'Self',
    'adminDashboard.confirmRemoveParticipant': 'Remove {email}?',
    'adminDashboard.representativeLabel': 'Rep:',
    'adminDashboard.groupNameFallback': 'Group {letter}',
    'adminDashboard.csvHeaders': 'Position,Group Name,Representative,Members,Total Size',
    'adminDashboard.tabs': 'Tabs',
    'adminDashboard.mobileTabs': 'Mobile Tabs',
    'adminDashboard.ballotManagement': 'Ballot Management',
    'adminDashboard.startBallotSession': 'Start Ballot Session',
    'adminDashboard.ballotNotStarted': 'Ballot Not Started',
    'adminDashboard.ballotNotStartedDesc': 'Click "Start Ballot Session" to begin the drawing process.',
    'adminDashboard.ballotInProgress': 'Ballot in Progress',
    'adminDashboard.ballotInProgressDesc': 'Representatives are drawing positions. {drawn} of {total} groups have completed their draws.',
    'adminDashboard.ballotCompletedDesc': 'All groups have drawn their positions. Results are now available.',
    'adminDashboard.noApprovedGroups': 'No Approved Groups',
    'adminDashboard.noApprovedGroupsDesc': 'You need approved groups before running the ballot.',
    'adminDashboard.readyToDraw': 'Ready to Draw',
    'adminDashboard.readyToDrawDesc': '{count} approved groups ready for ballot draw.',
    'adminDashboard.finalAllocationOrder': 'Final Allocation Order',
    'adminDashboard.viewPublicResults': 'View Public Results',
    'adminDashboard.exportDetailedResults': 'Export Detailed Results',
    'adminDashboard.groupsWaitingApproval': '{count} groups waiting for approval',
    
    // Results Page
    'results.noResultsYet': 'No Results Yet',
    'results.notDrawnYet': 'The ballot hasn\'t been drawn yet. Results will be published here once available.',
    'results.ballotResults': 'Ballot Results',
    'results.drawnOn': 'Drawn on',
    'results.at': 'at',
    'results.totalGroups': 'Total Groups',
    'results.totalParticipants': 'Total Participants',
    'results.findYourGroup': 'Find Your Group',
    'results.enterEmail': 'Enter your email address',
    'results.search': 'Search',
    'results.position': 'Position #{position}',
    'results.unnamedGroup': 'Unnamed Group',
    'results.members': '{count} members',
    'results.member': '{count} member',
    'results.representative': 'Representative',
    'results.notFound': 'Not Found',
    'results.emailNotInGroup': 'This email was not part of any group in the ballot.',
    'results.allocationOrder': 'Allocation Order',
    'results.downloadResults': 'Download Results',
    'results.completeAllocationList': 'Complete Allocation List',
    'results.allParticipants': 'All participants in draw order',
    'results.downloadExcel': 'Download Excel',
    'results.participants': 'participants',
    'results.rep': 'Rep',
    'results.backToHome': 'Back to Home',
    'results.checkMyStatus': 'Check My Status',
    'results.unknown': 'Unknown',
    
    // Admin Settings
    'adminSettings.title': 'Admin Settings',
    'adminSettings.description': 'Manage your admin account and system settings',
    'adminSettings.password': 'Change Password',
    'adminSettings.passwordShort': 'Password',
    'adminSettings.admins': 'Admin Users',
    'adminSettings.users': 'User Management', 
    'adminSettings.system': 'System',
    'adminSettings.changePassword': 'Change Password',
    'adminSettings.changingPassword': 'Changing Password...',
    
    // Session Management
    'adminSettings.currentSession': 'Current Session',
    'adminSettings.loggedInAs': 'Logged in as',
    'adminSettings.loginTime': 'Login time',
    'adminSettings.totalAdmins': 'Total admins',
    'adminSettings.sessionStatus': 'Session status',
    'adminSettings.valid': 'Valid',
    'adminSettings.expired': 'Expired',
    'adminSettings.refreshData': 'Refresh Data',
    'adminSettings.backToDashboard': 'Back to Dashboard',
    
    // Password Change
    'adminSettings.currentPassword': 'Current Password',
    'adminSettings.newPassword': 'New Password',
    'adminSettings.confirmPassword': 'Confirm New Password',
    'adminSettings.minCharacters': 'Minimum 6 characters',
    'adminSettings.passwordsNoMatch': 'New passwords do not match',
    'adminSettings.passwordChanged': 'Password changed successfully',
    'adminSettings.currentPasswordRequired': 'Current password is required',
    
    // Admin Management
    'adminSettings.addNewAdmin': 'Add New Admin',
    'adminSettings.username': 'Username',
    'adminSettings.addAdmin': 'Add Admin',
    'adminSettings.existingAdmins': 'Existing Admins',
    'adminSettings.created': 'Created',
    'adminSettings.lastLogin': 'Last Login',
    'adminSettings.actions': 'Actions',
    'adminSettings.current': 'Current',
    'adminSettings.default': 'Default',
    'adminSettings.confirmRemoveAdmin': 'Are you sure you want to remove admin \'{username}\'?',
    'adminSettings.adminAdded': 'Admin added successfully',
    'adminSettings.adminRemoved': 'Admin removed successfully',
    
    // User Management
    'adminSettings.addNewParticipant': 'Add New Participant',
    'adminSettings.simpleSystem': 'Simple System',
    'adminSettings.superadminDesc': 'Superadmin: Manages the system (you)',
    'adminSettings.participantsDesc': 'Participants: Everyone else in the ballot (no password needed)',
    'adminSettings.emailAddress': 'Email Address',
    'adminSettings.emailPlaceholder': 'user@example.com',
    'adminSettings.participantDesc': 'Participant will be added to the ballot. They can login with just their email (no password). Use "Create Group from Existing Users" below to form groups.',
    'adminSettings.wechatId': 'WeChat ID',
    'adminSettings.wechatPlaceholder': 'Enter WeChat ID',
    'adminSettings.wechatRequired': 'WeChat ID is required for participant identification.',
    'adminSettings.addUser': 'Add User',
    'adminSettings.confirmRemoveUser': 'Remove user {email}? This will also remove them from any groups.',
    'adminSettings.confirmRemoveFromGroup': 'Remove {email} from their group? They will become ungrouped.',
    
    // System Management
    'adminSettings.systemManagement': 'System Management',
    'adminSettings.dangerZone': 'Danger Zone',
    'adminSettings.dangerWarning': 'These actions cannot be undone. Please use with caution.',
    'adminSettings.clearBallotOnly': 'Clear Ballot Data Only',
    'adminSettings.clearAllData': 'Clear All Data',
    'adminSettings.clearBallotDesc': 'Clear Ballot Data Only: Removes all participants, groups, ballot results, and sessions. Keeps admin accounts.',
    'adminSettings.clearAllDesc': 'Clear All Data: Removes everything including admin accounts (except default admin).',
    'adminSettings.dataStorage': 'Data Storage',
    'adminSettings.dataStorageDesc': 'All data is stored locally in your browser\'s localStorage. No data is sent to external servers. To backup your data, use the export features in the admin dashboard.',
    
    // Confirmation dialogs
    'adminSettings.confirmClearAll1': '⚠️ This will delete ALL ballot data and reset the system. This cannot be undone. Are you sure?',
    'adminSettings.confirmClearAll2': 'This includes all participants, groups, results, and admin accounts except the default admin. Continue?',
    'adminSettings.confirmClearBallot1': '⚠️ This will delete ALL ballot data (participants, groups, results) but keep admin accounts. Continue?',
    'adminSettings.confirmClearBallot2': 'This includes all participants, groups, ballot results, and sessions. Admin accounts will be preserved. Are you sure?',
    'adminSettings.confirmRemoveGroup': 'Remove this group?',
    'adminSettings.dataClearedSuccess': 'Data cleared successfully',
    'adminSettings.operationFailed': 'Operation failed',
    
    
    
    
    
    // Group Formation Page
    'group.createGroup': 'Create Your Group',
    'group.joinGroup': 'Join Existing Group',
    'group.createDescription': "You'll be the Group Representative and submit the ballot entry for everyone",
    'group.joinDescription': 'Join an existing group that has space for more members',
    'group.createGroupTab': 'Create Group',
    'group.joinGroupTab': 'Join Group',
    'group.membersTitle': 'Group Members',
    'group.youRepresentative': '(You - Representative)',
    'group.representative': '👑 Rep',
    'group.remove': 'Remove',
    'group.addParticipants': 'Add Registered Participants',
    'group.selectParticipant': 'Select a participant to add',
    'group.addByEmail': 'Or Add by Email (Groups: 1-3 people)',
    'group.emailPlaceholder': 'member@email.com',
    'group.addMember': '+ Add',
    'group.groupSize': 'Group Size: {current}/3 members',
    'group.allMembersRegistered': '⚠️ All members must be registered participants',
    'group.submitGroup': 'Submit Group Entry',
    'group.creatingGroup': 'Creating Group...',
    'group.cancel': 'Cancel',
    'group.availableGroups': 'Available Groups',
    'group.noAvailableGroups': 'No available groups to join',
    'group.tryCreating': 'Try creating your own group instead',
    'group.viewResultsBtn': 'View Results',
    'group.yourGroup': 'Your Group',
    'group.alreadyInGroup': "You're already part of a group",
    'group.groupDetails': 'Group Details',
    'group.groupRepLabel': 'Representative:',
    'group.groupSizeLabel': 'Group Size:',
    'group.statusLabel': 'Status:',
    'group.pendingApproval': '⏳ Pending Approval',
    'group.approved': '✅ Approved',
    'group.locked': '🔒 Locked',
    'group.membersLabel': 'Members',
    'group.viewFullStatus': 'View Full Status',
    'group.backToHome': 'Back to Home',
    
    // Common
    'common.error': '⚠️ Error:',
    'common.loading': 'Loading...',
    'common.success': '✅',
    'common.warning': '⚠️',
    'common.info': '💡',
    'common.close': '×',
    'common.ok': 'OK',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.confirm': 'Confirm',
  },
  zh: {
    // Header
    'header.home': '抽票系统',
    'header.register': '注册/登录',
    'header.adminLogin': '管理员登录',
    'header.createGroup': '创建群组',
    'header.myStatus': '我的状态',
    'header.results': '结果',
    'header.join': '🔐 加入',
    'header.dashboard': '⚙️ 控制台',
    'header.logout': '🚪 退出',
    'header.adminName': '管理员: {name}',
    'header.userLogout': '退出',
    'header.confirmLogout': '退出当前用户会话？',
    'header.openMainMenu': '打开主菜单',
    
    // Landing Page
    'landing.title': '公平透明',
    'landing.subtitle': '抽票系统',
    'landing.description': '通过我们的随机抽票系统获得票券机会。组建小组，提交报名，让公平决定一切。',
    'landing.participants': '参与者',
    'landing.groups': '已组建群组',
    'landing.ballotComplete': '抽票完成',
    'landing.howItWorks': '如何运作：',
    'landing.step1': '注册您的兴趣',
    'landing.step2': '组建小组（1-3人）',
    'landing.step3': '随机抽票决定顺序',
    'landing.joinBallot': '加入抽票',
    'landing.joinDescription': '立即注册参与公平的抽票系统。',
    'landing.registerLogin': '注册 / 登录',
    'landing.checkStatus': '查看状态',
    'landing.administrator': '管理员？',
    'landing.adminLogin': '🔐 管理员登录',
    'landing.youreRegistered': '您已注册！',
    'landing.readyToForm': '准备好组建小组或查看您的状态。',
    'landing.createJoinGroup': '创建/加入群组',
    'landing.checkMyStatus': '查看我的状态',
    'landing.adminMode': '管理员模式',
    'landing.adminDescription': '管理参与者、群组并运行抽票。',
    'landing.goToDashboard': '前往控制台',
    'landing.viewResults': '查看抽票结果',
    
    // Status Page
    'status.youreRegistered': '您已注册！',
    'status.noGroupYet': '尚未加入群组',
    'status.noGroupDescription': '您还没有创建或加入群组。您需要加入群组才能参与抽票。',
    'status.whatsNext': '接下来做什么？',
    'status.createGroupStep': '创建群组',
    'status.becomeRepresentative': '成为代表并提交抽票申请',
    'status.waitForApproval': '等待审批',
    'status.adminValidation': '管理员将验证您的群组成员',
    'status.ballotDraw': '抽票',
    'status.randomSelection': '随机选择决定分配顺序',
    'status.createGroupButton': '创建群组',
    'status.backToHome': '返回首页',
    'status.checkStatus': '查看您的状态',
    'status.enterEmail': '输入您的邮箱查看参与状态',
    'status.emailAddress': '邮箱地址',
    'status.checkStatusButton': '查看状态',
    'status.notRegisteredYet': '还没有注册？',
    'status.registerNow': '立即注册 →',
    'status.notRegistered': '未注册',
    'status.emailNotRegistered': '邮箱 {email} 未注册参与此次抽票。',
    'status.registerNowButton': '立即注册',
    'status.checkDifferentEmail': '查看其他邮箱',
    'status.viewResults': '查看结果',
    'status.yourStatus': '您的状态',
    'status.registered': '已注册',
    'status.readyToParticipate': '准备参与',
    'status.groupApproved': '群组已批准',
    'status.ballotComplete': '抽票完成',
    'status.pendingApproval': '等待审批',
    'status.readyToDraw': '准备抽签',
    'status.drawComplete': '抽签完成',
    'status.readyForBallotDraw': '准备抽票',
    'status.resultsAvailable': '结果可用',
    'status.waitingForAdminValidation': '等待管理员验证',
    'status.clickToDrawPosition': '点击抽签您的位置！',
    'status.waitingForRepresentative': '等待代表抽签',
    'status.positionDrawn': '位置 {position} 已抽签',
    'status.groupDetails': '群组详情',
    'status.representative': '代表',
    'status.groupSize': '群组规模',
    'status.members': '成员',
    'status.you': '您',
    'status.rep': '代表',
    'status.timeToDraw': '抽签时间！',
    'status.groupReadyForBallot': '您的群组准备抽票',
    'status.asRepresentative': '作为 {groupName} 的代表，您现在可以抽签您的位置。',
    'status.clickToDraw': '点击下面的按钮随机抽签您群组的位置。',
    'status.drawing': '抽签中...',
    'status.drawPosition': '抽签位置',
    'status.ballotStatus': '抽票状态',
    'status.ballotInProgress': '抽票进行中',
    'status.groupCompletedDraw': '您的群组已完成抽签。等待其他群组完成。',
    'status.canDrawNow': '您现在可以在上面抽签您的位置。',
    'status.ballotResults': '抽票结果',
    'status.positionInQueue': '您的群组在分配队列中的位置是 #{position}',
    'status.drawnOn': '抽签日期',
    'status.totalGroups': '总群组数',
    'status.totalParticipants': '总参与者数',
    'status.refreshStatus': '刷新状态',
    'status.asRepresentativeOf': '作为',
    'status.youCanNowDraw': '的代表，您现在可以抽签您的位置。',
    'status.clickButtonToDraw': '点击下面的按钮随机抽取您群组的位置。',
    'status.groupDrawnPosition': '您的群组已抽取位置 #{position}！',
    'status.waitingForAllGroups': '等待所有群组完成抽签...',
    'status.continue': '继续',
    
    // Group Formation Page
    'group.create.title': '创建群组',
    'group.create.description': '组建最多3人的群组参与抽票',
    'group.create.tab': '创建群组',
    'group.join.title': '加入群组',
    'group.join.description': '加入需要更多成员的现有群组',
    'group.join.tab': '加入群组',
    'group.create.membersTitle': '群组成员',
    'group.create.youRepresentative': '您（代表）',
    'group.create.rep': '代表',
    'group.create.remove': '移除',
    'group.create.addParticipants': '添加已注册参与者：',
    'group.create.selectParticipant': '选择参与者...',
    'group.create.addByEmail': '或通过邮箱添加：',
    'group.create.memberPlaceholder': '输入邮箱地址',
    'group.create.add': '添加',
    'group.create.groupSize': '群组规模',
    'group.create.membersLower': '成员',
    'group.create.registeredRequired': '所有成员必须是已注册的参与者',
    'group.create.submit': '创建群组',
    'group.create.submitting': '创建中...',
    'group.create.cancel': '取消',
    'group.create.invalidEmail': '请输入有效的邮箱地址',
    'group.create.duplicateEmail': '此邮箱已在群组中',
    'group.create.maxMembers': '群组最多可有3名成员',
    'group.create.memberCount': '群组至少需要1名成员（您自己）',
    'group.join.availableGroups': '可加入的群组',
    'group.join.noGroups': '没有可加入的群组',
    'group.join.createInstead': '尝试创建您自己的群组',
    'group.join.tip': '提示',
    'group.join.submit': '加入群组',
    'group.join.submitting': '加入中...',
    'group.accessRequired': '需要注册',
    'group.registerFirst': '您需要先注册才能创建或加入群组。',
    'group.registerNow': '立即注册',
    'group.ballotComplete': '抽票完成',
    'group.formationClosed': '群组组建已关闭。抽票已完成。',
    'group.viewResults': '查看结果',
    'group.existing.title': '您的群组',
    'group.existing.description': '您已经是群组的一员',
    'group.existing.details': '群组详情',
    'group.existing.representative': '代表',
    'group.existing.you': '您',
    'group.existing.groupSize': '群组规模',
    'group.existing.members': '成员',
    'group.existing.status': '状态',
    'group.existing.statusPending': '等待审批',
    'group.existing.statusApproved': '已批准',
    'group.existing.statusLocked': '抽票完成',
    'group.existing.membersTitle': '成员',
    'group.existing.rep': '代表',
    'group.existing.viewFullStatus': '查看完整状态',
    'group.existing.backToHome': '返回首页',
    'group.error': '错误',
    'group.groupRepresentative': '代表：{name}',
    'group.groupCreated': '创建时间：{date}',
    'group.groupMembers': '成员：{members}',
    'group.spacesAvailable': '还有{count}个位置',
    'group.selectGroupTip': '选择一个群组并点击加入群组',
    
    // Demo Data
    'demo.loadDemoData': '🧪 加载演示数据',
    'demo.loadSampleData': '加载测试用的示例数据',
    'demo.dataLoaded': '演示数据加载成功！您现在可以测试应用程序。',
    'demo.failedToLoad': '加载演示数据失败：{error}',
    
    // User Auth Page
    'userAuth.joinBallot': '加入抽票',
    'userAuth.welcomeBack': '欢迎回来',
    'userAuth.registerDescription': '注册参与抽票活动',
    'userAuth.loginDescription': '使用您注册的邮箱登录',
    'userAuth.register': '注册',
    'userAuth.login': '登录',
    'userAuth.createAccount': '创建您的账户',
    'userAuth.loginToAccount': '登录到您的账户',
    'userAuth.emailAddress': '电子邮箱',
    'userAuth.emailPlaceholder': 'your@email.com',
    'userAuth.wechatId': '微信号',
    'userAuth.wechatPlaceholder': '输入您的微信号',
    'userAuth.createAccountBtn': '创建账户',
    'userAuth.loginBtn': '登录',
    'userAuth.creatingAccount': '正在创建账户...',
    'userAuth.loggingIn': '正在登录...',
    'userAuth.noPasswordRequired': '📧 无需密码 - 稍后只需使用邮箱登录',
    'userAuth.passwordFreeLogin': '🔒 免密码登录 - 我们会识别您的邮箱',
    'userAuth.emailForLogin': '输入您用于注册的邮箱',
    'userAuth.backToHome': '← 返回首页',
    'userAuth.needAdminAccess': '需要管理员权限？',
    'userAuth.adminLogin': '管理员登录',
    
    // Admin Login Page
    'adminLogin.title': '管理员登录',
    'adminLogin.description': '安全访问抽票管理面板',
    'adminLogin.adminAccessOnly': '🔒 仅管理员访问',
    'adminLogin.username': '用户名',
    'adminLogin.usernamePlaceholder': '输入管理员用户名',
    'adminLogin.password': '密码',
    'adminLogin.passwordPlaceholder': '输入密码',
    'adminLogin.signIn': '登录',
    'adminLogin.signingIn': '正在登录...',
    'adminLogin.backToSite': '← 返回公共网站',
    'adminLogin.regularUser': '普通用户？',
    'adminLogin.userRegistration': '用户注册/登录',
    'adminLogin.accessOnly': '仅管理员访问',
    'adminLogin.adminAccessDescription': '这是安全的管理员区域。只有授权的管理员才能访问系统管理功能。',
    'adminLogin.error': '错误',
    'adminLogin.defaultAccounts': '🚀 默认登录账户',
    'adminLogin.standardAdmin': '标准管理员：',
    'adminLogin.superAdmin': '超级管理员：',
    'adminLogin.changePassword': '⚠️ 首次登录后请更改默认密码',
    'adminLogin.firstTimeSetup': '🚀 首次设置',
    'adminLogin.manageParticipants': '管理参与者',
    'adminLogin.manageDescription': '添加、删除和查看所有参与者',
    'adminLogin.runBallot': '运行抽票',
    'adminLogin.runDescription': '执行公平的随机抽票',
    'adminLogin.viewResultsFeature': '查看结果',
    'adminLogin.viewDescription': '导出和分析抽票结果',
    
    // Admin Navigation
    'admin.dashboard': '控制台',
    'admin.settings': '管理员设置',
    
    // Admin Dashboard
    'adminDashboard.title': '管理控制台',
    'adminDashboard.welcome': '欢迎使用抽票管理面板',
    'adminDashboard.totalParticipants': '总参与者',
    'adminDashboard.pendingGroups': '待审批群组',
    'adminDashboard.approvedGroups': '已批准群组',
    'adminDashboard.lockedGroups': '已锁定群组',
    'adminDashboard.overview': '概览',
    'adminDashboard.participants': '参与者',
    'adminDashboard.groups': '群组',
    'adminDashboard.ballot': '抽票',
    'adminDashboard.startBallot': '开始抽票',
    'adminDashboard.confirmStartBallot': '开始抽票会话？代表将能够抽签他们的位置。',
    'adminDashboard.pending': '待处理',
    'adminDashboard.approved': '已批准', 
    'adminDashboard.ballot-ready': '准备抽票',
    'adminDashboard.ballot-drawn': '已抽签',
    'adminDashboard.locked': '已锁定',
    'adminDashboard.viewResults': '查看结果',
    'adminDashboard.recentActivity': '最近活动',
    'adminDashboard.addParticipant': '添加参与者',
    'adminDashboard.email': '邮箱',
    'adminDashboard.wechatId': '微信号',
    'adminDashboard.addUser': '添加用户',
    'adminDashboard.adding': '正在添加...',
    'adminDashboard.participantsList': '参与者列表',
    'adminDashboard.groupsList': '群组列表',
    'adminDashboard.ballotStatus': '抽票状态',
    'adminDashboard.groupCreated': '群组已创建（{count}名成员）',
    'adminDashboard.ballotCompleted': '✅ 抽票已完成，共{count}个群组',
    'adminDashboard.add': '添加',
    'adminDashboard.addButton': '添加',
    'adminDashboard.remove': '移除',
    'adminDashboard.edit': '编辑',
    'adminDashboard.approve': '批准',
    'adminDashboard.reject': '拒绝',
    'adminDashboard.representative': '代表',
    'adminDashboard.members': '名成员',
    'adminDashboard.member': '名成员',
    'adminDashboard.status': '状态',
    'adminDashboard.actions': '操作',
    'adminDashboard.role': '角色',
    'adminDashboard.user': '用户',
    'adminDashboard.noActivity': '暂无最近活动',
    'adminDashboard.createdAt': '创建于',
    'adminDashboard.statusInGroup': '已入组',
    'adminDashboard.statusNoGroup': '未入组',
    'adminDashboard.noActivityYet': '暂无活动',
    'adminDashboard.quickActions': '快速操作',
    'adminDashboard.makeRepresentative': '设为代表',
    'adminDashboard.removeRepresentativeRole': '移除代表角色',
    'adminDashboard.userRole': '用户',
    'adminDashboard.repRole': '代表',
    'adminDashboard.emailAddress': '邮箱地址',
    'adminDashboard.wechatIdLabel': '微信号',
    'adminDashboard.wechatIdPlaceholder': '输入微信号用于身份识别',
    'adminDashboard.addedBy': '添加者',
    'adminDashboard.date': '日期',
    'adminDashboard.groupStatus': '群组状态',
    'adminDashboard.groupMembers': '群组（{count}名成员）',
    'adminDashboard.readyForBallot': '准备抽票',
    'adminDashboard.waitingForDraw': '等待代表抽签',
    'adminDashboard.positionDrawn': '已抽到第{position}号位',
    'adminDashboard.ballotCompletedStatus': '抽票已完成',
    'adminDashboard.noGroupsYet': '暂无群组',
    'adminDashboard.noParticipantsYet': '暂无参与者',
    'adminDashboard.participantsHeader': '参与者 ({count})',
    'adminDashboard.roleRepresentative': '代表',
    'adminDashboard.roleUser': '用户',
    'adminDashboard.addedByAdmin': '管理员',
    'adminDashboard.addedBySelf': '自己',
    'adminDashboard.confirmRemoveParticipant': '移除 {email}？',
    'adminDashboard.representativeLabel': '代表:',
    'adminDashboard.groupNameFallback': '群组 {letter}',
    'adminDashboard.csvHeaders': '位置,群组名称,代表,成员,总人数',
    'adminDashboard.tabs': '标签页',
    'adminDashboard.mobileTabs': '移动端标签页',
    'adminDashboard.ballotManagement': '抽票管理',
    'adminDashboard.startBallotSession': '开始抽票',
    'adminDashboard.ballotNotStarted': '抽票未开始',
    'adminDashboard.ballotNotStartedDesc': '点击"开始抽票"开始抽签过程。',
    'adminDashboard.ballotInProgress': '抽票进行中',
    'adminDashboard.ballotInProgressDesc': '代表正在抽签。{drawn}个群组（共{total}个）已完成抽签。',
    'adminDashboard.ballotCompletedDesc': '所有群组都已抽完位置。结果现已可查看。',
    'adminDashboard.noApprovedGroups': '无已批准群组',
    'adminDashboard.noApprovedGroupsDesc': '运行抽票前需要有已批准的群组。',
    'adminDashboard.readyToDraw': '准备抽签',
    'adminDashboard.readyToDrawDesc': '{count}个已批准群组准备抽票。',
    'adminDashboard.finalAllocationOrder': '最终分配顺序',
    'adminDashboard.viewPublicResults': '查看公开结果',
    'adminDashboard.exportDetailedResults': '导出详细结果',
    'adminDashboard.groupsWaitingApproval': '{count}个群组等待审批',
    
    // Results Page
    'results.noResultsYet': '暂无结果',
    'results.notDrawnYet': '抽票尚未开始。结果将在抽票完成后公布。',
    'results.ballotResults': '抽票结果',
    'results.drawnOn': '抽票日期',
    'results.at': '时间',
    'results.totalGroups': '总群组数',
    'results.totalParticipants': '总参与者数',
    'results.findYourGroup': '查找您的群组',
    'results.enterEmail': '请输入您的邮箱地址',
    'results.search': '搜索',
    'results.position': '第{position}号位',
    'results.unnamedGroup': '未命名群组',
    'results.members': '{count}名成员',
    'results.member': '{count}名成员',
    'results.representative': '代表',
    'results.notFound': '未找到',
    'results.emailNotInGroup': '此邮箱未加入任何参与抽票的群组。',
    'results.allocationOrder': '分配顺序',
    'results.downloadResults': '下载结果',
    'results.completeAllocationList': '完整分配名单',
    'results.allParticipants': '所有参与者按抽签顺序',
    'results.downloadExcel': '下载Excel',
    'results.participants': '名参与者',
    'results.rep': '代表',
    'results.backToHome': '返回首页',
    'results.checkMyStatus': '查看我的状态',
    'results.unknown': '未知',
    
    // Admin Settings
    'adminSettings.title': '管理员设置',
    'adminSettings.description': '管理您的管理员账户和系统设置',
    'adminSettings.password': '更改密码',
    'adminSettings.passwordShort': '密码',
    'adminSettings.admins': '管理员用户',
    'adminSettings.users': '用户管理', 
    'adminSettings.system': '系统',
    'adminSettings.changePassword': '更改密码',
    'adminSettings.changingPassword': '正在更改密码...',
    
    // Session Management
    'adminSettings.currentSession': '当前会话',
    'adminSettings.loggedInAs': '登录身份',
    'adminSettings.loginTime': '登录时间',
    'adminSettings.totalAdmins': '管理员总数',
    'adminSettings.sessionStatus': '会话状态',
    'adminSettings.valid': '有效',
    'adminSettings.refreshData': '刷新数据',
    'adminSettings.backToDashboard': '返回控制台',
    
    // Password Change
    'adminSettings.currentPassword': '当前密码',
    'adminSettings.newPassword': '新密码',
    'adminSettings.confirmPassword': '确认新密码',
    'adminSettings.minCharacters': '最少6个字符',
    'adminSettings.passwordsNoMatch': '新密码不匹配',
    'adminSettings.passwordChanged': '密码修改成功',
    'adminSettings.currentPasswordRequired': '需要当前密码',
    
    // Admin Management
    'adminSettings.addNewAdmin': '添加新管理员',
    'adminSettings.username': '用户名',
    'adminSettings.addAdmin': '添加管理员',
    'adminSettings.existingAdmins': '现有管理员',
    'adminSettings.created': '创建时间',
    'adminSettings.lastLogin': '最后登录',
    'adminSettings.actions': '操作',
    'adminSettings.current': '当前',
    'adminSettings.default': '默认',
    'adminSettings.confirmRemoveAdmin': '确定要删除管理员 \'{username}\' 吗？',
    'adminSettings.adminAdded': '管理员添加成功',
    'adminSettings.adminRemoved': '管理员删除成功',
    
    // User Management
    'adminSettings.addNewParticipant': '添加新参与者',
    'adminSettings.simpleSystem': '简单系统',
    'adminSettings.superadminDesc': '超级管理员：管理系统（您）',
    'adminSettings.participantsDesc': '参与者：抽票中的其他人（无需密码）',
    'adminSettings.emailAddress': '邮箱地址',
    'adminSettings.emailPlaceholder': 'user@example.com',
    'adminSettings.participantDesc': '参与者将被添加到抽票中。他们可以仅用邮箱登录（无需密码）。使用下面的"从现有用户创建群组"来组建团队。',
    'adminSettings.wechatId': '微信号',
    'adminSettings.wechatPlaceholder': '输入微信号',
    'adminSettings.wechatRequired': '微信号用于参与者身份识别，必填。',
    'adminSettings.addUser': '添加用户',
    'adminSettings.confirmRemoveUser': '删除用户 {email}？这也会将他们从任何群组中移除。',
    'adminSettings.confirmRemoveFromGroup': '将 {email} 从群组中移除？他们将成为未分组状态。',
    
    // System Management
    'adminSettings.systemManagement': '系统管理',
    'adminSettings.dangerZone': '危险区域',
    'adminSettings.dangerWarning': '这些操作无法撤销。请谨慎使用。',
    'adminSettings.clearBallotOnly': '仅清除抽票数据',
    'adminSettings.clearAllData': '清除所有数据',
    'adminSettings.clearBallotDesc': '仅清除抽票数据：删除所有参与者、群组、抽票结果和会话。保留管理员账户。',
    'adminSettings.clearAllDesc': '清除所有数据：删除包括管理员账户在内的所有内容（默认管理员除外）。',
    'adminSettings.dataStorage': '数据存储',
    'adminSettings.dataStorageDesc': '所有数据存储在您浏览器的本地存储中。不会发送数据到外部服务器。要备份数据，请使用管理控制台中的导出功能。',
    
    // Confirmation dialogs
    'adminSettings.confirmClearAll1': '⚠️ 这将删除所有抽票数据并重置系统。此操作无法撤销。确定吗？',
    'adminSettings.confirmClearAll2': '这包括所有参与者、群组、结果和管理员账户（默认管理员除外）。继续？',
    'adminSettings.confirmClearBallot1': '⚠️ 这将删除所有抽票数据（参与者、群组、结果）但保留管理员账户。继续？',
    'adminSettings.confirmClearBallot2': '这包括所有参与者、群组、抽票结果和会话。管理员账户将被保留。确定吗？',
    'adminSettings.confirmRemoveGroup': '删除此群组？',
    'adminSettings.dataClearedSuccess': '数据清除成功',
    'adminSettings.operationFailed': '操作失败',
    
    
    
    
    
    
    
    // Group Formation Page
    'group.createGroup': '创建您的群组',
    'group.joinGroup': '加入现有群组',
    'group.createDescription': '您将成为群组代表，为所有人提交抽票申请',
    'group.joinDescription': '加入一个有空位的现有群组',
    'group.createGroupTab': '创建群组',
    'group.joinGroupTab': '加入群组',
    'group.membersTitle': '群组成员',
    'group.youRepresentative': '（您 - 代表）',
    'group.representative': '👑 代表',
    'group.remove': '移除',
    'group.addParticipants': '添加已注册参与者',
    'group.selectParticipant': '选择要添加的参与者',
    'group.addByEmail': '或通过邮箱添加（群组：1-3人）',
    'group.emailPlaceholder': 'member@email.com',
    'group.addMember': '+ 添加',
    'group.groupSize': '群组规模：{current}/3 成员',
    'group.allMembersRegistered': '⚠️ 所有成员必须是已注册参与者',
    'group.submitGroup': '提交群组申请',
    'group.creatingGroup': '正在创建群组...',
    'group.cancel': '取消',
    'group.availableGroups': '可用群组',
    'group.noAvailableGroups': '没有可加入的群组',
    'group.tryCreating': '试着创建您自己的群组',
    'group.joinSelected': '加入选中的群组',
    'group.joiningGroup': '正在加入群组...',
    'group.needRegister': '您需要先注册才能创建群组。',
    'group.yourGroup': '您的群组',
    'group.alreadyInGroup': '您已经是群组的一部分',
    'group.groupDetails': '群组详情',
    'group.groupRepLabel': '代表：',
    'group.groupSizeLabel': '群组规模：',
    'group.statusLabel': '状态：',
    'group.pendingApproval': '⏳ 等待审批',
    'group.approved': '✅ 已批准',
    'group.locked': '🔒 已锁定',
    'group.membersLabel': '成员',
    'group.viewFullStatus': '查看完整状态',
    'group.backToHome': '返回首页',
    
    // Common
    'common.error': '⚠️ 错误：',
    'common.loading': '加载中...',
    'common.success': '✅',
    'common.warning': '⚠️',
    'common.info': '💡',
    'common.close': '×',
    'common.ok': '确定',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.add': '添加',
    'common.remove': '移除',
    'common.back': '返回',
    'common.next': '下一步',
    'common.previous': '上一步',
    'common.submit': '提交',
    'common.reset': '重置',
    'common.confirm': '确认',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Load saved language from localStorage or default to English
    return (localStorage.getItem('ticket-ballot-language') as Language) || 'en';
  });

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('ticket-ballot-language', newLanguage);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const currentTranslations = translations[language] as Record<string, string>;
    const fallbackTranslations = translations['en'] as Record<string, string>;
    let text = currentTranslations[key] || fallbackTranslations[key] || key;
    
    // Replace parameters like {name}, {count}, etc.
    if (params) {
      Object.keys(params).forEach(param => {
        text = text.replace(new RegExp(`{${param}}`, 'g'), String(params[param]));
      });
    }
    
    return text;
  };

  useEffect(() => {
    // Update document language attribute
    document.documentElement.lang = language;
  }, [language]);

  const value: LanguageContextType = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}